site_name: MDM-Learnings
site_url: https://Kurrams.github.io/MDM-Learnings/

nav:
    
    - Android-MDM: 
        - General: 
            - ApplicationManagement:
                - 'Android_MDM/General/ApplicationManagement-InternalAppSharing.md'
            - Troubleshooting: 
                - 'Android_MDM/General/Troubleshooting-Safemode.md'
                - 'Android_MDM/General/WifiCallingPrioritization.md'
                - 'Android_MDM/General/advanced-troubleshooting.md'
            - Android Enterprise: 
                - 'Android_MDM/General/AndroidEnterprise/AndroidZeroTouch.md'
                - 'Android_MDM/General/AndroidEnterprise/android-enterprise-overview.md'
        - WorksapaceONE: 
            - 'Android_MDM/WorkspaceONE/UnderConstruction.md'
        - Google MDM: 
            - 'Android_MDM/GoogleMDM/UnderConstruction.md'
        - MicrosoftIntune: 
            - 'Android_MDM/Intune/UnderConstruction.md'
    - iOS-MDM:
         - General: 
            - Apple Business Manager:
                - 'Apple/General/general-info.md'
                - 'Apple/General/notes.md'
         - WorksapaceONE: 
            - 'Apple/WorkspaceONE/UnderConstruction.md'
            - 'Apple/WorkspaceONE/MultiUseCase.md'
         - Google MDM: 
            - 'Apple/GoogleMDM/UnderConstruction.md'
         - Intune:
            - 'Apple/General/UnderConstruction.md'
    - General: 
            - 'General/General.md'
            - 'General/known-OS.md'
            - 'General/app-stores.md'
            - 'General/Standards.md'
    - Aboutme: 'aboutme.md'
    - Index: 'index.md'

theme:
  name: material
  features:
   - navigation.tabs
   - navigation.tabs.sticky
   - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow