site_name: MDM-Learnings
site_url: https://Kurrams.github.io/MDM-Learnings/

nav:
    
    - Android-MDM: 
        - General: 
            - ApplicationManagement:
                - Internal App Sharing and Testing via Google Play Console: 'Android_MDM/General/ApplicationManagement-InternalAppSharing.md'
            - Troubleshooting: 
                - Safemode: 'Android_MDM/General/Troubleshooting-Safemode.md'
                - Wifi Calling Prioritization on Samsung Phones: 'Android_MDM/General/WifiCallingPrioritization.md'
            - Android Enterprise: 
                Android Zero Touch: 'Android_MDM/General/AndroidEnterprise/AndroidZeroTouch.md'
        - WorksapaceONE: 
            - 'Android_MDM/WorkspaceONE/UnderConstruction.md'
        - Google MDM: 
            - 'Android_MDM/GoogleMDM/UnderConstruction.md'
        - MicrosoftIntune: 
            - 'Android_MDM/Intune/UnderConstruction.md'
    - Apple-MDM:
         - General: 
            - Apple Business Manager:
                - Apple Business Manager: 'Apple/General/AppleBusinessManager.md'
         - WorksapaceONE: 
            - 'Apple/WorkspaceONE/UnderConstruction.md'
         - Google MDM: 
            - 'Apple/GoogleMDM/UnderConstruction.md'
         - Intune:
            - 'Apple/General/UnderConstruction.md'
    - Aboutme: 'aboutme.md'
    - Index: 'index.md'

theme:
  name: material
  features:
   - navigation.tabs
   - navigation.tabs.sticky
   - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow